name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
            
      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci
        
      - name: Build Application
        run: npm run build
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: webhosting32.1blu.de
          protocol: ftps
          server-dir: /www/food-code/
          local-dir: ./dist/browser/
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
